"""test

Revision ID: 896ffc5c4804
Revises: 03d0ce486f1e
Create Date: 2025-12-05 21:38:49.060108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '896ffc5c4804'
down_revision: Union[str, Sequence[str], None] = '03d0ce486f1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
